### ISSUE TITLE
add CONTRIBUTING.md file

### ISSUE THREAD

**Issue by chadxz** [codeforhuntsville/Frontier#10]
Add contribution guidelines to the repo so that people have a clear path to contributing to the project. [Here](https://github.com/puppetlabs/puppet/blob/master/CONTRIBUTING.md) is an example, but specify the rules that make sense to you. The [github help article on Contributing Guidelines](https://github.com/blog/1184-contributing-guidelines) may also be of help.

**Comment by mjcarroll** [comment]
We should also have a contributor agreement (CLA)

http://wiki.civiccommons.org/Contributor_Agreements

**Comment by chadxz** [comment]
I'll create a separate ticket for CLA as it deserves some discussion

**Comment by chadxz** [comment]
I'd like for the Contributing guidelines to state that even "Owners" of the project should follow the contribution guidelines, namely NOT committing directly to master unless there's a good reason for doing so. All contributions to the project should be peer reviewed by at least one other person, and this is the best way to ensure that happens.

**Comment by dustywusty** [comment]
:+1:

**Comment by dannagle** [comment]
:+1:

**Comment by Nedlinin** [comment]
:+1:

**Comment by itsamenathan** [comment]
:+1

**Comment by dannagle** [comment]
Am I correct to assume all submitted code should be MIT licensed?
