### ISSUE TITLE
CLA for the project

### ISSUE THREAD

**Issue by chadxz** [codeforhuntsville/Frontier#16]
in #10 it was brought up that we should consider adding a CLA to the project. I'm not a lawyer, so I don't know if it is needed for our project. If it is, I think it would probably be important to get an actual lawyer to help us write the CLA document and know what information to collect from the person to make the CLA actually viable in court.

I did a cursory search online, and it wasn't really clear to me if a project with multiple contributors that wasn't backed by any specific business would need a CLA. I know of plenty of open source projects that are MIT-licensed that have tons of contributors that do not require a CLA to contribute to.

Anyway, would probably be worth consulting a lawyer about it if it's a cause for concern.

**Comment by chadxz** [comment]
https://www.clahub.com/ seems like a pretty decent solution to this that has a nice integration with Github. It's open source as well, so we could host our own version of it if we want it on the c4h domain

**Comment by larrymason** [comment]
Here is a first draft of a CLA based on the NodeJS (Joyent) CLA it gives us some text to edit... see what you think, feel free to edit... https://docs.google.com/document/d/1hC_77Y66CEcVpHPUjc96XInrKDXzJSQVhgP6HLgJ730/edit

**Comment by spearna** [comment]
Looks good Larry. Seemed to cover everything from a layman perspective.
