### ISSUE TITLE
Delegation

### ISSUE THREAD

**Issue by dannagle** [codeforhuntsville/Frontier#17]
I had some time to spare, so I set up VM, forked the project, installed the packages, launched Node.js, and my immediate result was:

```
Error retrieving restaurants
TypeError: restaurants.map is not a function
```

I started to track down the bug, but I found this project seems pretty bare-bones. Could we discuss task delegation at the next meeting? I don't want to step on anybody's toes at such an early state.

**Comment by chadxz** [comment]
Yeah we have only put a few hours into it, with little error handling.
Sounds like the body.results on the server side is returning null or
undefined, which would need to be handled and return an empty array to the
front end.

As far as task delegation, i think that would be a great idea for the next
meeting. It would be great to load up some use stories and acceptance
criteria into the github issues tracker, so people can pick a task and run
with it.

**Comment by chadxz** [comment]
@dannagle can you see if https://github.com/chadxz/Frontier/tree/bugfix/guard-no-restaurants-array-result (PR #19) fixes the problem you were experiencing? If not, can you please update #18 with additional details about the issue (such as the response coming back from `GET /restaurants`) so that it can be addressed? Thanks :)

As for the task delegation, I'd like to keep that topic flowing here if possible!

**Comment by spearna** [comment]
For delegation, I agree with Chad. Get a good vision laid out to define the goal. Then follow agile principles of defining small, bite sized issues that anyone can claim, complete and put back. An ad hoc path allowing for first come first serve. 
Dan, I don't think there's a worry of stepping on toes, so go as fast as you want.

**Comment by chrisbeaman** [comment]
@spearna @chadxz @dannagle Let's discuss task delegation at hack night tomorrow night.

**Comment by chadxz** [comment]
From what i gathered today, this is still something to be fleshed out at a future meeting. Or we can just discuss it here, which would probably be a good start. 

My feeling is that we need a decent backlog of well defined tasks for people to just dive into. I'm happy to work with people when i have time and answer questions as they crop up.

I'd like to focus on features of the application, which we can derive from the mockups that our designers are providing to us. Today we got a 7 pg mock up that will be a lot of help in getting us going. 

https://drive.google.com/open?id=0B4q4gt-CbXUTbklmaEtXRHpZNmM&amp;authuser=0

**Comment by chadxz** [comment]
closing this. I discussed a path forward with @chrisbeaman today and we're gonna get started on providing a path for contribution via github issues ready to be worked on.
