### ISSUE TITLE
Brainstorm List of Layers

### ISSUE THREAD

**Issue by robert-hanson** [codeforhuntsville/Frontier#22]

**Comment by robert-hanson** [comment]
Food/drink
1.  Restaurants
2.  Local Restaurants
3.  Bars
4.  Delivery
5.  coffee

Active
1.  Exercise classes/groups
   a.  Yoga
   b.  Dancing
   c.  Crossfit
   d.  …

Entertainment
1.  Live Music
2.  Comedy/Stand up show
3.  Outdoor events
   a.  Art/music festival
   b.  Food trucks
   c.  Light show
   d.  …
4.  Sports events (I know we don’t have the stars anymore ☹)

Public Resources
1.  Parks
2.  Public Restrooms
3.  Parking
4.  Gas Stations

Family friendly category?

**Comment by chrisbeaman** [comment]
Here's both a master list of layers as well as links to public APIs for almost every one: https://docs.google.com/document/d/1OABjdiwiQp-dECF59WS2jY7sJuv3NOFKJCakkDfLMlo/edit?usp=sharing

**Comment by chrisbeaman** [comment]
Layers and APIs are now here: https://github.com/codeforhuntsville/Frontier/wiki/Masterlist-of-layers-and-public-APIs
