### ISSUE TITLE
Evaluate ESRI Koop as a data provider middleware

### ISSUE THREAD

**Issue by mjcarroll** [codeforhuntsville/Frontier#46]
ESRI has a suite of tools called Koop: https://github.com/Esri/koop

This is a node.js/express application that allows different data providers to be exposed as either GeoJSON or ESRI-style REST endpoints.

The advantage of using a tool like this is that there are already several providers for common geo-data (ArcGIS, Github, Gist, Socrata, Census data, CKAN), and it's pretty easily extensible.

The open question is whether it can interface with the city's ArcGIS instance, or if it is bound to ArcGIS online.

**Comment by chadxz** [comment]
I talked to @mjcarroll about this. He said someone did try to audit ESRI Koop and it wasn't working with the city's ArcGIS instance because they're exposing "MapLayers" instead of what Koop expects which are "FeatureServers". We decided we're just gonna roll with a custom solution for now.
